// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtNu4FhDfVgtuBVCX_9l8IIdYmhGNhXeg',
    appId: '1:906357188964:web:56f72367613ce3063af271',
    messagingSenderId: '906357188964',
    projectId: 'voyage-4fb27',
    authDomain: 'voyage-4fb27.firebaseapp.com',
    storageBucket: 'voyage-4fb27.firebasestorage.app',
    measurementId: 'G-41L1KY95BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT6Im-i7xGEojzH0JxJCtReIAt_u42Bac',
    appId: '1:906357188964:android:91f5441792189b0d3af271',
    messagingSenderId: '906357188964',
    projectId: 'voyage-4fb27',
    storageBucket: 'voyage-4fb27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIEpbhiOmNIl03KvBC2oEXoS26xNpoL_I',
    appId: '1:906357188964:ios:f0d3e027b47341be3af271',
    messagingSenderId: '906357188964',
    projectId: 'voyage-4fb27',
    storageBucket: 'voyage-4fb27.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIEpbhiOmNIl03KvBC2oEXoS26xNpoL_I',
    appId: '1:906357188964:ios:f0d3e027b47341be3af271',
    messagingSenderId: '906357188964',
    projectId: 'voyage-4fb27',
    storageBucket: 'voyage-4fb27.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtNu4FhDfVgtuBVCX_9l8IIdYmhGNhXeg',
    appId: '1:906357188964:web:9a948ac06781899f3af271',
    messagingSenderId: '906357188964',
    projectId: 'voyage-4fb27',
    authDomain: 'voyage-4fb27.firebaseapp.com',
    storageBucket: 'voyage-4fb27.firebasestorage.app',
    measurementId: 'G-CHGSWHRCVL',
  );
}